// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTNiSbk7PflHAMRLFfJsbjqDuHcTVUhQ',
    appId: '1:148982236938:web:6500c3b24a2a20cd391cf3',
    messagingSenderId: '148982236938',
    projectId: 'crud-agenda6',
    authDomain: 'crud-agenda6.firebaseapp.com',
    storageBucket: 'crud-agenda6.appspot.com',
    measurementId: 'G-J9GN639KQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGyCnp6f4ruzmr3-hoe-efE7lsxXsqBg0',
    appId: '1:148982236938:android:bdafc34e5b0349c8391cf3',
    messagingSenderId: '148982236938',
    projectId: 'crud-agenda6',
    storageBucket: 'crud-agenda6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1bAYTa4mSkvI8HbzRSJhFcH1ykjaOaBc',
    appId: '1:148982236938:ios:c22a94cba7bbbffb391cf3',
    messagingSenderId: '148982236938',
    projectId: 'crud-agenda6',
    storageBucket: 'crud-agenda6.appspot.com',
    androidClientId: '148982236938-2b361eng5vkip210lm1puae0u01q9emp.apps.googleusercontent.com',
    iosClientId: '148982236938-gbn0rs4l9sjvdgivegn8oiaq3k2o1cfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenda07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1bAYTa4mSkvI8HbzRSJhFcH1ykjaOaBc',
    appId: '1:148982236938:ios:c22a94cba7bbbffb391cf3',
    messagingSenderId: '148982236938',
    projectId: 'crud-agenda6',
    storageBucket: 'crud-agenda6.appspot.com',
    androidClientId: '148982236938-2b361eng5vkip210lm1puae0u01q9emp.apps.googleusercontent.com',
    iosClientId: '148982236938-gbn0rs4l9sjvdgivegn8oiaq3k2o1cfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenda07',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkTNiSbk7PflHAMRLFfJsbjqDuHcTVUhQ',
    appId: '1:148982236938:web:b25fa7e8f0ec929a391cf3',
    messagingSenderId: '148982236938',
    projectId: 'crud-agenda6',
    authDomain: 'crud-agenda6.firebaseapp.com',
    storageBucket: 'crud-agenda6.appspot.com',
    measurementId: 'G-830EBZVF4N',
  );
}
